/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/6LrSXNM2pjC
 */
import { Button } from "@/components/ui/button"
import { DropdownMenuTrigger, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuContent, DropdownMenu } from "@/components/ui/dropdown-menu"
import Link from "next/link"
import Image from 'next/image'
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"

export function TestDashboard() {
  return (
    (<div className="flex flex-col h-screen">
      <header
        className="flex items-center justify-between h-16 px-6 bg-gray-800 text-white">
        <h1 className="font-semibold text-lg">Test Automation Dashboard</h1>
        <div className="flex items-center">
          <Button className="mr-4" size="icon" variant="ghost">
            <svg
              className=" h-5 w-5 text-white"
              fill="none"
              height="24"
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              viewBox="0 0 24 24"
              width="24"
              xmlns="http://www.w3.org/2000/svg">
              <path
                d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" />
              <circle cx="12" cy="12" r="3" />
            </svg>
            <span className="sr-only">Settings</span>
          </Button>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button size="icon" variant="ghost">
                <svg
                  className=" h-5 w-5 text-white"
                  fill="none"
                  height="24"
                  stroke="currentColor"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth="2"
                  viewBox="0 0 24 24"
                  width="24"
                  xmlns="http://www.w3.org/2000/svg">
                  <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
                  <circle cx="12" cy="7" r="4" />
                </svg>
                <span className="sr-only">User menu</span>
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuItem>Profile</DropdownMenuItem>
              <DropdownMenuItem>Settings</DropdownMenuItem>
              <DropdownMenuSeparator />
              <DropdownMenuItem>Logout</DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </header>
      <div className="flex flex-1">
        <aside className="w-64 bg-gray-100 p-6">
          <h2 className="font-semibold text-gray-800 mb-4">Test Suites</h2>
          <ul className="space-y-2">
            <li>
              <Link className="text-gray-600 hover:text-gray-900" href="#">
                Suite 1
              </Link>
            </li>
            <li>
              <Link className="text-gray-600 hover:text-gray-900" href="#">
                Suite 2
              </Link>
            </li>
            <li>
              <Link className="text-gray-600 hover:text-gray-900" href="#">
                Suite 3
              </Link>
            </li>
          </ul>
          <h2 className="font-semibold text-gray-800 my-4">Test Cases</h2>
          <ul className="space-y-2">
            <li>
              <Link className="text-gray-600 hover:text-gray-900" href="#">
                Case 1
              </Link>
            </li>
            <li>
              <Link className="text-gray-600 hover:text-gray-900" href="#">
                Case 2
              </Link>
            </li>
            <li>
              <Link className="text-gray-600 hover:text-gray-900" href="#">
                Case 3
              </Link>
            </li>
          </ul>
        </aside>
        <main className="flex-1 p-6">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            <div className="p-6 border rounded-lg">
              <h2 className="font-semibold text-gray-800 mb-4">Test Execution Trends</h2>
              <Image
                src="https://tweets-codecademy.s3.eu-central-1.amazonaws.com/placeholder.png"
                alt="Placeholder"
                className="w-full rounded-lg"
                width="500"
                height="250"
              />
            </div>
            <div className="p-6 border rounded-lg">
              <h2 className="font-semibold text-gray-800 mb-4">Test Summary</h2>
              <ul className="space-y-2">
                <li>
                  Total Tests: <span className="font-bold">120</span>
                </li>
                <li>
                  Passed: <span className="font-bold text-green-600">100</span>
                </li>
                <li>
                  Failed: <span className="font-bold text-red-600">20</span>
                </li>
              </ul>
            </div>
          </div>
          <div className="mt-6 p-6 border rounded-lg">
            <h2 className="font-semibold text-gray-800 mb-4">Recent Test Results</h2>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Test Case</TableHead>
                  <TableHead>Result</TableHead>
                  <TableHead>Execution Time</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                <TableRow>
                  <TableCell>Case 1</TableCell>
                  <TableCell className="text-green-600">Passed</TableCell>
                  <TableCell>3 min</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>Case 2</TableCell>
                  <TableCell className="text-red-600">Failed</TableCell>
                  <TableCell>5 min</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>Case 3</TableCell>
                  <TableCell className="text-green-600">Passed</TableCell>
                  <TableCell>2 min</TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </div>
        </main>
      </div>
    </div>)
  );
}
